<?php
bolt_decrypt( __FILE__ , 'xqLBYl'); return 0;
##!!!##Rkaqnamhr6ydn6FcfaysmISwsKyYiaWgoKihs52uoXdGRrGvoVx/qKuvsa6hd0ZGn6idr69ckKWpobarqqFGt0ZFrLGeqKWfXKKxqp+wpauqXKSdqqCooWRgrqGtsaGvsGhcf6irr7GuoVxgqqG0sGhcYKOxna6gXHlcqrGoqGVGRbdGRUWgnbChm6Chop2xqLCbsKWpobarqqGbr6GwZF59r6Wda4CknaedXmV3RkZFRa6hsLGuqlxgqqG0sGRgrqGtsaGvsGV3RkW5RrlG