<?php
bolt_decrypt( __FILE__ , 'lYgoIT'); return 0;
##!!!##QkKtq51YgaSkraWhppmsnZR8mayZmpmrnZSLnZ2cnapzQkKbpJmrq1h8mayZmpmrnYudnZydqlidsKydppyrWIudnZydqkKzQlhYWFhnYmJCWFhYWFhiWIudnZxYrKCdWJmoqKShm5msoaemX6tYnJmsmZqZq51mQlhYWFhYYkJYWFhYWGJYeKqdrK2qpliup6GcQlhYWFhYYmdCWFhYWKitmqShm1ieraabrKGnpliqraZgYUJYWFhYs0JYWFhYWFhYWFysoKGrZXabmaSkYICnpKGcmbGLnZ2cnapycpukmaurYXNCWFhYWLVCQrVC