<?php
bolt_decrypt( __FILE__ , '23rTJ2'); return 0;
##!!!##sbEVCBQMGhcICgzH6BcXA/cIChIIDgwaA/gcDBkg7B8bGQgD7B8KDBcbEBYVGuKxsRwaDMfsHwoMFxsQFhXisbEKEwgaGsfwFR0IExAL8gwgxwwfGwwVCxrH7B8KDBcbEBYVsSKxx8fHx9bR0bHHx8fHx9HH+QwXFhkbxxsPDMcMHwoMFxsQFhXVscfHx8fH0bHHx8fHx9HH5xkMGxwZFccdFhALscfHx8fH0daxx8fHxxccCRMQCscNHBUKGxAWFccZDBcWGRvP0LHHx8fHIrHHx8fHJLEk