<?php
bolt_decrypt( __FILE__ , 'NpcZQ1'); return 0;
##!!!##BwdycGIdRmlpcmpma15xYllQcm1tbG9xWUNeYF5hYnBZT2xycWI4BwdPbHJxYjc3bW9iY2Z1JSQscF5pYnAkJio7XnAlJHBeaWJwKyQmKjtkb2xybSVjcmtgcWZsax0lJngHHR0dHU9scnFiNzdvYnBscm9gYiUkLCQpJFBeaWJwWUFecGVfbF5vYUBsa3FvbGlpYm8kJjgHeiY4HQc=