<?php
bolt_decrypt( __FILE__ , 'qygMFM'); return 0;
##!!!##Ozufkp6WpKGSlJZRcqGhjX6glZadpI15o2w7O6akllF6nZ2mnpqfkqWWjXWSpZKTkqSWjXadoKKmlp+ljX6glZadbDs7lJ2SpKRRcqGho5KapJKdUZappZaflaRRfqCVlp07rDtRUVFRoaOgpZaUpZaVUVWlkpOdlm5RUViZo5ChlqOXoKOekp+UlpCSoaGjkpqkkp1YbDtRUVFRO1FRUVGhppOdmpRRVaWanpakpZKeoaRuUZeSnaSWbDuuOw==