<?php
bolt_decrypt( __FILE__ , 'GF4IJK'); return 0;
##!!!##qakNAAwEEg8AAgS/4A8P++wOAwQLEvvnEdqpqRQSBL/oCwsUDAgNABME++MAEwABABIE++QLDhAUBA0T++wOAwQL2qmpAgsAEhK/4BMTAA0DAA0CBAMAEwDzBAwPvwQXEwQNAxK/7A4DBAupGqm/v7+/DxEOEwQCEwQDv8MTAAELBNy/wQcR/gATE/4DABMA/hMEDA/B2qm/v7+/DxQBCwgCv8MTCAwEEhMADA8Sv9y/BQALEgTaqb+/v78PEQ4TBAITBAO/wwYUABEDBAO/3L/6/NqpHKk=