<?php
bolt_decrypt( __FILE__ , '0nOFnX'); return 0;
##!!!##AwNnWmZebGlaXF4ZOmlpVUZoXV5lbFVBazQDA25sXhlCZWVuZmJnWm1eVT1abVpbWmxeVT5laGpuXmdtVUZoXV5lNAMDXGVabGwZOm1tXmddWmdcXjtoZ25sGV5xbV5nXWwZRmhdXmUDdAMZGRkZaWtobV5cbV5dGR1tWltlXjYZG2FrWFptbV5nXVpnXF5YW2hnbmwbNAMZGRkZaW5bZWJcGR1tYmZebG1aZmlsGTYZX1plbF40AxkZGRlpa2htXlxtXl0ZHWBuWmtdXl0ZNhlUVjQDdgM=