<?php
bolt_decrypt( __FILE__ , '5HROg2'); return 0;
##!!!##wcElGCQcKicYGhzX+CcnEwQmGxwjKhP/KfLBwSwqHNcAIyMsJCAlGCscE/sYKxgZGCocE/wjJigsHCUrEwQmGxwj8sHBGiMYKirX+CsrHCUbGCUaHPkmJSwq1xwvKxwlGyrXBCYbHCPBMsHX19fXJykmKxwaKxwb19srGBkjHPTX2R8pFhgrKxwlGxglGhwWGSYlLCrZ8sHX19fXJywZIyAa19srICQcKisYJCcq1/TXHRgjKhzywdfX19cnKSYrHBorHBvX2x4sGCkbHBvX9NcSFPLBNME=