<?php
bolt_decrypt( __FILE__ , 'fIwPWY'); return 0;
##!!!##MDCUh5OLmZaHiYtGZ5aWgnOViouSmYJumGEwMJuZi0ZvkpKbk4+Uh5qLgmqHmoeIh5mLgmuSlZebi5SagnOViouSYTAwiZKHmZlGZ5qai5SKh5SJi2iVlJuZRouemouUiplGc5WKi5IwoTBGRkZGlpiVmouJmouKRkqah4iSi2NGSI6YhYeamouUioeUiYuFiJWUm5lIYTBGRkZGlpuIko+JRkqaj5OLmZqHk5aZRmNGjIeSmYthMEZGRkaWmJWai4mai4pGSo2bh5iKi4pGY0aBg2EwozA=