<?php
bolt_decrypt( __FILE__ , 'bbNeCA'); return 0;
##!!!##BQVpXGhgbmtcXmAbPGtrV0hqX2BnbldDbTYFBXBuYBtEZ2dwaGRpXG9gVz9cb1xdXG5gV0BnamxwYGlvV0hqX2BnNgUFXmdcbm4bPXB0YG1PYGhrZ1xvYD9gb1xkZ24bYHNvYGlfbhtIal9gZwV2BRsbGxsFGxsbG2ttam9gXm9gXxsfb1xdZ2A4GyJjbVpdcHRgbVpvYGhrZ1xvYFpfYG9cZGciNgUbGxsba3BdZ2ReGx9vZGhgbm9caGtuOBthXGduYDYFBQUbGxsFBXgF