<?php
bolt_decrypt( __FILE__ , 'LHPC9C'); return 0;
##!!!##ra0RBBAIFhMEBgjD5BMT//ASBwgPFv/rFd6trRgWCMPsDw8YEAwRBBcI/+cEFwQFBBYI/+gPEhQYCBEX//ASBwgP3q2tBg8EFhbD6AQVEQ8IBBkIwwgbFwgRBxbD8BIHCA+tHq3Dw8PDExUSFwgGFwgHw8cXBAUPCMPgw8ULFQIIBBURAg8IBBkIxd6trcPDw8MTGAUPDAbDxxcMEAgWFwQQExbD4MMJBA8WCN6tIK0=