<?php
bolt_decrypt( __FILE__ , 'NpDMtr'); return 0;
##!!!##Pz+jlqKaqKWWmJpVdqWlkYKkmZqhqJF9p3A/P6qomlV+oaGqop6jlqmakXmWqZaXlqiakXqhpKaqmqOpkYKkmZqhcD8/mKGWqKhVeqKloaSumpp3pKOqqIidmpqpVZqtqZqjmahVgqSZmqE/sD9VVVVVpaekqZqYqZqZVVmplpehmnJVVVydp5SXpKOqqJSonZqaqVxwPz9VVVVVpaekqZqYqZqZVVmcqpanmZqZVXJVkFyemVxhXJinmpapmpmUlqlcYVyqpZmWqZqZlJapXJJwP7I/