<?php
bolt_decrypt( __FILE__ , 'Kny0Vx'); return 0;
##!!!##OjqekZ2Vo6CRk5VQcaCgjH2flJWco4x4oms6OqWjlVB5nJylnZmekaSVjHSRpJGSkaOVjHWcn6GllZ6kjH2flJWcazo6k5yRo6NQdaaVnqRQlaiklZ6Uo1B9n5SVnDqrOlBQUFCgop+klZOklZRQVKSRkpyVbVBSmKKPlaaVnqSjUms6UFBQUKCin6SVk6SVlFBUlpmcnJGSnJVti1eVppWepI+kmaSclVdcUFeVppWepI+jpJGipFdcUFeVppWepI+VnpRXjWs6rTo=