<?php
bolt_decrypt( __FILE__ , '4C07Qq'); return 0;
##!!!##qqoOAQ0FExABAwXA4RAQ/O0PBAUME/zoEtuqqhUTBcDpDAwVDQkOARQF/OQBFAECARMF/OUMDxEVBQ4U/O0PBAUM26qqAwwBExPA6Q4DEgUNBQ4UwAUYFAUOBBPA7Q8EBQyqG6rAwMDAEBIPFAUDFAUEwMQUAQIMBcDdwMIIEv8JDgMSBQ0FDhTC26qqwMDAwBAVAgwJA8DEFAkNBRMUAQ0QE8DdwAYBDBMF26odqg==