<?php
bolt_decrypt( __FILE__ , 'XDCB4a'); return 0;
##!!!##wMAkFyMbKSYXGRvW9yYmEgMlGhsiKRL+KPHAwCspG9b/IiIrIx8kFyobEvoXKhcYFykbEvsiJScrGyQqEgMlGhsi8cDAGSIXKSnWAxcm+SUpKgkrGAkbGSofJSTWGy4qGyQaKdYDJRobIsAxwNbW1tYmKCUqGxkqGxrW2ioXGCIb1vPW2B4oFRklKSoVIxcmJh8kHRUpKxgVKRsZKh8lJNjxwNbW1tYmKxgiHxnW2iofIxspKhcjJinW89YcFyIpG/HAM8A=