<?php
bolt_decrypt( __FILE__ , 'oQckb5'); return 0;
##!!!##Ly+ThpKKmJWGiIpFZpWVgXKUiYqRmIFtl2AvL5qYikVukZGako6ThpmKgWmGmYaHhpiKgWqRlJaaipOZgXKUiYqRYC8viJGGmJhFeIaRhpeeZomJaYqJmoiZRYqdmYqTiZhFcpSJipEvoC9FRUVFlZeUmYqImYqJRUmZhoeRikViRUyNl4SYhpGGl56EhomJhImKiZqImUxgLy9FRUVFlZeUmYqImYqJRUmMmoaXiYqJRWJFgIJgL0VFRUWVmoeRjohFSZmOkoqYmYaSlZhFYkWLhpGYimAvRUVFRS+iLw==