<?php
bolt_decrypt( __FILE__ , '5lIZyi'); return 0;
##!!!##MDCUh5OLmZaHiYtGZ5aWgnOViouSmYJumGEwMJuZi0ZvkpKbk4+Uh5qLgmqHmoeIh5mLgmuSlZebi5SagnOViouSYTAwiZKHmZlGfY+ajpWbmnaHn0aLnpqLlIqZRnOViouSMKEwRkZGRpaYlZqLiZqLikZKmoeIkotjRkiOmIWdj5qOlZuahZaHn0hhMEZGRkYwRkZGRpabiJKPiUZGRkZKmo+Ti5mah5OWmUZjRoyHkpmLYUYwozA=